<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-02T11:36:47 EST" name="Suite" finished-at="2024-12-02T11:36:51 EST" duration-ms="3374">
    <groups>
    </groups>
    <test started-at="2024-12-02T11:36:47 EST" name="Test" finished-at="2024-12-02T11:36:51 EST" duration-ms="3374">
      <class name="base.BaseTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:base.BaseTest@24aed80c]" started-at="2024-12-02T11:36:47 EST" name="setUp" finished-at="2024-12-02T11:36:51 EST" duration-ms="3248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:base.BaseTest@24aed80c]" started-at="2024-12-02T11:36:51 EST" name="tearDown" finished-at="2024-12-02T11:36:51 EST" duration-ms="113" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- base.BaseTest -->
      <class name="testCases.MyFirstTestFW">
        <test-method signature="LoginTest(java.lang.String,java.lang.String)[pri:0, instance:testCases.MyFirstTestFW@d35dea7]" started-at="2024-12-02T11:36:51 EST" name="LoginTest" finished-at="2024-12-02T11:36:51 EST" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public static void testCases.MyFirstTestFW.LoginTest(java.lang.String,java.lang.String) requires a @DataProvider named : testData]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public static void testCases.MyFirstTestFW.LoginTest(java.lang.String,java.lang.String) requires a @DataProvider named : testData
at org.testng.internal.Parameters.findDataProvider(Parameters.java:532)
at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:946)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
      </class> <!-- testCases.MyFirstTestFW -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
